Serialize the DingTalk we input
    serialize: the function that transform the DingTalk to a sequence
    le: the result of serialize

In [48]:
import numpy as np


def serialize(DingTalk):
    l=[]
    DingTalk=str(DingTalk)
    for i in range(0,len(DingTalk)-2):
        if i%3==0 :
            l.append((DingTalk[i:i+3]))
    return l
my_DingTalk=17816125215
le=serialize(my_DingTalk)
print(le)


['178', '161', '252']


In this step, we convert this sequence of numbers into 3x3 numpy matrix A
    le: the sequence we got in the last step
    v: the transform result

In [50]:
import numpy as np

for i in range(0,len(le)):
    le[i]=[le[i][0],le[i][1],le[i][2]]
    le[i]=[int(i) for i in le[i]]
v=np.array(le)
print(v)

[[1 7 8]
 [1 6 1]
 [2 5 2]]


As for matrix inversion, we first judge whether the matrix is reversible, and then inverse the matrix
We use the function transpose to get the transpose of v

In [62]:

def inverse_matrix(matrix):
    if np.linalg.det(matrix)>0:
        in_matrix=np.linalg.inv(matrix)
        return in_matrix
    else:
        return "error,the matrix cannot be inverse"
inverse_v=inverse_matrix(v)
print("the inverse of v :\n%s"%inverse_v)

transpose_v=v.transpose()
print("the transpose of v :\n%s"%transpose_v)

res=v*transpose_v
print("the result of v * transpose :\n%s"%res)

the inverse of v :
error,the matrix cannot be inverse
the transpose of v :
[[1 1 2]
 [7 6 5]
 [8 1 2]]
the result of v * transpose :
[[ 1  7 16]
 [ 7 36  5]
 [16  5  4]]


In [64]:
sub_v=np.array([v[0],v[2]])
print(sub_v)

[[1 7 8]
 [2 5 2]]
